version: "2"  # Обязательное поле для версии 2.x

run:
  timeout: 5m
  go: "1.23.2"
  concurrency: 4
  skip-dirs:
    - vendor

linters:
  enable:
    # Базовые линтеры
    - govet        # анализатор от Go
    - staticcheck  # комплексный статический анализатор
    - unused       # проверка неиспользуемых констант, переменных, функций, типов
    - ineffassign  # проверка неэффективного присваивания
    
    # Dead code detection (using modern linters)
    - ineffassign  # проверка неиспользуемых присваиваний
    
    # Integration verification linters
    - unparam      # проверка неиспользуемых параметров функций
    - goconst      # проверка повторяющихся строк, которые можно вынести в константы
    - unconvert    # проверка ненужных преобразований типов
    
    # Дополнительные линтеры
    - errcheck     # проверка обработки ошибок
    - gosec        # проверка безопасности
    - misspell     # проверка орфографии в комментариях
    - prealloc     # проверка возможности предварительного выделения памяти для слайсов
    - bodyclose    # проверяет, что HTTP-ответы правильно закрываются
    - whitespace   # проверка правильного использования пробелов
    - nilerr       # проверка возврата nil вместо ошибки
    
    # Phase integration checks
    - gocritic     # множественные проверки качества кода
    - revive       # замена golint с дополнительными правилами

formatters:
  enable:
    - gofmt        # форматирование кода по стилю Go

issues:
  max-issues-per-linter: 30
  max-same-issues: 100
  
  exclude-rules:
    # Игнорировать ошибки в тестовых файлах
    - path: "_test\\.go"
      linters:
        - errcheck
    
    # Отключить проверки безопасности для тестовых файлов
    - path: "_test\\.go"
      linters:
        - gosec

linters-settings:
  govet:
    check-shadowing: true
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  
  # Dead code and integration verification settings
  unused:
    check-exported: true  # проверять экспортированные функции
  
  unparam:
    check-exported: true  # проверять неиспользуемые параметры в экспортированных функциях
  
  gocritic:
    enabled-tags:
      - diagnostic      # диагностические проверки
      - style          # стилевые проверки  
      - performance    # проверки производительности
      - experimental   # экспериментальные проверки
    disabled-checks:
      - importShadow   # отключить проверку затенения импортов
  
  revive:
    rules:
      # Проверка интеграции компонентов
      - name: unused-parameter
        severity: warning
      - name: unused-receiver
        severity: warning
      - name: unreachable-code
        severity: error
      - name: early-return
        severity: warning
      
      # Phase integration verification rules  
      - name: context-as-argument
        severity: warning
      - name: flag-parameter
        severity: warning
      - name: function-result-limit
        arguments: [3]  # максимум 3 возвращаемых значения
      - name: argument-limit
        arguments: [5]  # максимум 5 аргументов функции